export default {
  accessList: 'array',
  blockHash: 'hex',
  blockNumber: 'number',
  chainId: 'hex',
  from: 'hex',
  gas: 'number',
  gasPrice: 'number',
  hash: 'hex',
  input: 'hex',
  maxFeePerGas: 'number',
  maxPriorityFeePerGas: 'number',
  nonce: 'number',
  r: 'hex',
  s: 'hex',
  to: 'hex',
  transactionIndex: 'number',
  type: 'number',
  v: 'hex',
  value: 'number',
}
